### ISSUE TITLE
Ticket nicht lesbar

### ISSUE THREAD

**Issue by fcaspar** [rumpeltux/onlineticket#11]
Moin!

Würde jemand freundlicherweise einmal nachschauen, warum das Decoding nicht funktioniert?
Ich bin ratlos... :(

Vielen Dank im Voraus! :)

Ps: pycryptodome ist installiert.

---

Please remove the deprecated python3-crypto package and install python3-pycryptodome instead.
Note: signature verification is disabled due to missing pycryptodome package.
Traceback (most recent call last):
  File "onlineticket.py", line 543, in <module>
    ot = OT(binary_ticket)
  File "onlineticket.py", line 86, in __init__
    self.header = self.dict_read(self.generic)
  File "onlineticket.py", line 118, in dict_read
    dat = val[3](self, res)
  File "onlineticket.py", line 464, in signature_decode
    decoded = asn1.decode(self.read(50))[0]
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/decoder.py", line 1289, in __call__
    value, substrate = concreteDecoder.valueDecoder(
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/decoder.py", line 501, in valueDecoder
    asn1Object, trailing = self._decodeComponents
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/decoder.py", line 451, in _decodeComponents
    component, substrate = decodeFun(substrate, **options)
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/decoder.py", line 1164, in __call__
    raise error.SubstrateUnderrunError(
pyasn1.error.SubstrateUnderrunError: 58<20 at <TagSet object at 0x7febc30995b0 tags 192:0:2>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onlineticket.py", line 547, in <module>
    ot = OT(fixed)
  File "onlineticket.py", line 86, in __init__
    self.header = self.dict_read(self.generic)
  File "onlineticket.py", line 118, in dict_read
    dat = val[3](self, res)
  File "onlineticket.py", line 474, in signature_validity
    pubkey = get_pubkey(issuer=res['carrier'],
  File "onlineticket.py", line 430, in get_pubkey
    for cert_issuer, xid, pubkey in certreader:
ValueError: not enough values to unpack (expected 3, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onlineticket.py", line 550, in <module>
    (repr(ot), repr(fixed), ticket, e, f))
NameError: name 'ot' is not defined

**Decodierter Aztec-Code (via parsepdfs.sh):**
[NEXLU4.pdf-001.pbm.txt](https://github.com/rumpeltux/onlineticket/files/8756894/NEXLU4.pdf-001.pbm.txt)

**Comment by fcaspar** [comment]
Hmm. Liegt vielleicht in Decodier-Fehler vom Aztec vor?

Das Online-Tool von Aspose spuckt mir andere Ausgaben aus als parsepdfs.sh...
![2022-05-23 19_25_27-Generate Barcode Online](https://user-images.githubusercontent.com/50081787/169874997-018a51bd-0810-4d6f-bca3-b8dd63b64b4d.png)

**Comment by dariusarnold** [comment]
Hey, 
Onlinetickets der Deutschen Bahn verwenden das UIC-Barcodeformat (die Standards sind UIC 918.3, UIC 918.3* und UIC918.9). Die gesamte Binärstruktur besteht aus mehreren Records. Der erste Record ist immer der #UT-Record (Aufbau siehe [Tabelle Seite 44](https://web.archive.org/web/20200324055222/https://www.era.europa.eu/sites/default/files/library/docs/recommendation/era_rec122_tap_tsi_revision_recommendation_technical_document_b12_en.pdf)). Dieser beginnt immer mit den 3 statischen Bytes "#UT", dann zwei Bytes Headerversion (1 oder 2) usw. In deinem Barcode sind die ersten 3 Bytes aber "OTI". 
Wenn ich die ersten drei Bytes anpasse wird der Rest augenscheinlich korrekt gelesen. Ob das durch einen Fehler beim Auslesen verursacht wurde oder etwas anderes kann ich leider nicht sagen.

**Comment by fcaspar** [comment]
Danke für die Rückmeldung, Darius! 👍
