### ISSUE TITLE
Python script doesn't  work in Windows environment

### ISSUE THREAD

**Issue by paulbauriegel** [rumpeltux/onlineticket#3]
When  decoding the ticketdump using  Windows, the script run in some errors. When using exactly  the same ticketdump on Linux, everything works as expected.
[onlineticket.txt](https://github.com/rumpeltux/onlineticket/files/1524004/onlineticket.txt)

Error log:
`

```
conda create -n python2 python=2.7 anaconda

(python2) C:\Users\PaulBauriegel\Documents\Projekte\onlineticket>python onlineticket.py onlineticket.bin
ORIGINAL: 'OTI010080000060,\x02\x14s\xc3\xaeu\x0f\xc3\xac\xc3\xacjEs7\xc3\x88D^\xc2\x88\xc2\xbd*\xc2\x9cr\xc2\xb3\xc3\x89\x02\x14?T\xc2\xbe\x02H\xc3\x96D\xc2\x9c\xc2\x98\xc3\x81\xc3\xabJ\xc3\xb6\x1c\xc2\x80\x07\xc2\xac'
ZXING: 'OTI010080000060,\x02\x14s\xeeu\x0f\xec\xecjEs7\xc8D^\x88\xbd*\x9cr\xb3\xc9\x02\x14?T\xbe\x02H\xd6D\x9c\x98\xc1\xebJ\xf6\x1c\x80\x07\xac'
onlineticket.bin: Error: 22-octet short (orig); 3-octet short (zxing)
Traceback (most recent call last):
  File "onlineticket.py", line 452, in <module>
    ots.setdefault(ticket, []).append(OT(fix_zxing(ot)))
  File "onlineticket.py", line 60, in __init__
    self.header = self.dict_read(self.generic)
  File "onlineticket.py", line 92, in dict_read
    dat = val[3](self, res)
  File "onlineticket.py", line 398, in <lambda>
    lambda self, res: decoder.decode(self.read(50))),
  File "C:\ProgramData\Anaconda3\envs\python2\lib\site-packages\pyasn1\codec\ber\decoder.py", line 1049, in __call__
    raise error.SubstrateUnderrunError('%d-octet short' % (length - len(substrate)))
pyasn1.error.SubstrateUnderrunError: 3-octet short`
```

**Comment by rumpeltux** [comment]
The ticket is being decoded fine on Linux. As a hunch it may be due line-ending characters. Let me know if the fix I just pushed works.

**Comment by paulbauriegel** [comment]
Yes, it's working now!

**Comment by rumpeltux** [comment]
Great, glad to hear :)
